# Generated by Django 3.2.7 on 2024-04-23 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateTimeField()),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order_status', models.CharField(choices=[('to_be_paid', 'to_be_paid'), ('paid', 'paid'), ('shipped', 'shipped'), ('cancelled', 'cancelled')], max_length=50)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('product_url', models.URLField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.PositiveIntegerField()),
                ('category', models.CharField(max_length=50)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_index=True, max_length=50)),
                ('password', models.CharField(max_length=255)),
                ('email', models.EmailField(db_index=True, max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=255)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shopping_Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shoppingwebsites.products')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shoppingwebsites.users')),
            ],
        ),
        migrations.AddIndex(
            model_name='products',
            index=models.Index(fields=['product_name'], name='shoppingweb_product_6717e3_idx'),
        ),
        migrations.AddIndex(
            model_name='products',
            index=models.Index(fields=['price'], name='shoppingweb_price_b4fe98_idx'),
        ),
        migrations.AddIndex(
            model_name='products',
            index=models.Index(fields=['category'], name='shoppingweb_categor_f96547_idx'),
        ),
        migrations.AddIndex(
            model_name='products',
            index=models.Index(fields=['category', 'price'], name='shoppingweb_categor_a6daad_idx'),
        ),
        migrations.AddIndex(
            model_name='orders',
            index=models.Index(fields=['order_date'], name='shoppingweb_order_d_848408_idx'),
        ),
        migrations.AddIndex(
            model_name='orders',
            index=models.Index(fields=['order_status'], name='shoppingweb_order_s_9facee_idx'),
        ),
        migrations.AddIndex(
            model_name='orders',
            index=models.Index(fields=['order_date', 'order_status'], name='shoppingweb_order_d_fbb0da_idx'),
        ),
        migrations.AddField(
            model_name='order_details',
            name='order_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shoppingwebsites.orders'),
        ),
        migrations.AddField(
            model_name='order_details',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shoppingwebsites.products'),
        ),
    ]
