# Generated by Django 3.2.7 on 2024-04-12 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingwebsites', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='product_url',
            field=models.URLField(blank=True),
        ),
    ]
