# Generated by Django 3.2.7 on 2024-04-23 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingwebsites', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=5.0, max_digits=5),
        ),
    ]
