# Generated by Django 3.2.7 on 2024-04-23 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingwebsites', '0002_products_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='no_of_ratings',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
