# Generated by Django 3.2.7 on 2024-04-24 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingwebsites', '0003_products_no_of_ratings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='address',
        ),
    ]
